### ISSUE TITLE
Synchronize computers already imported not working

### ISSUE THREAD

**Issue by hvillanu** [pluginsGLPI/ocsinventoryng#215]
GLPI Version:
GLPI 9.4.2 Copyright (C) 2015-2019 Teclib' and contributors

Plugin Version:
ocsinventoryng | 1.6.0 | GPLv2+

The Plugin shows results on devices pending sync.

After push Synchonize button results screen goes blank and no action is taken.

PHP Log:
 Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /srv/www/htdocs/asset/inc/dbmysql.class.php:319 Stack trace: #0 /srv/www/htdocs/asset/plugins/ocsinventoryng/inc/ocsdbclient.class.php(403): DBmysql->fetch_assoc(false) #1 /srv/www/htdocs/asset/plugins/ocsinventoryng/inc/ocsdbclient.class.php(1020): PluginOcsinventoryngOcsDbClient->getComputerSections(Array, 4097, 1, 15, 0) #2 /srv/www/htdocs/asset/plugins/ocsinventoryng/inc/ocsclient.class.php(373): PluginOcsinventoryngOcsDbClient->getComputers(Array, '3') #3 /srv/www/htdocs/asset/plugins/ocsinventoryng/inc/ocsprocess.class.php(1149): PluginOcsinventoryngOcsClient->getComputer('3', Array) #4 /srv/www/htdocs/asset/plugins/ocsinventoryng/front/ocsng.sync.php(52): PluginOcsinventoryngOcsProcess::synchronizeComputer(Array) #5 {main} thrown in /srv/www/htdocs/asset/inc/dbmysql.class.php on line 319

![image](https://user-images.githubusercontent.com/52173795/60039884-615bdf00-967d-11e9-86f9-b1694911e155.png)

Any help will be appreciated

**Comment by laTruffe79** [comment]
Hello [same error as mine](https://github.com/pluginsGLPI/ocsinventoryng/issues/253)
